### ISSUE TITLE
Issues with GBC games

### ISSUE THREAD

**Issue by sincethenes** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#69]
Two I’ve found so far. In Jungle Book: Mowgli’s Wild Adventure, if you pause the game, once you unpause the only thing visible onscreen is the Mowgli’s sprite. The rest of the screen is just a light brown color. You can fix in game by pausing again and backing out to the world map to restart the level, but then all progress is erased. 

Another issue is in Klax. Once you reach level five, every time you complete half the level, it crashes and shows the screen attached. 
![4283280D-6603-4732-9A27-93311F10620D](https://user-images.githubusercontent.com/74995120/102716018-10936980-42a7-11eb-979e-73a121b8416b.jpeg)

**Comment by matthargett** [comment]
can you file the issues separately (eg move the Klax one to a new issue, and rename this one)? also, can you post the md5 hash of the ROMs you used? thanks!

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by Elrinth** [comment]
For me it works atleast in latest version.

**Comment by tjanas** [comment]
@sincethenes please confirm it is fixed so this issue can be closed

**Comment by sincethenes** [comment]
No, it still fails for me. Attached are some screenshots. Jungle book after pause/Klax now during level 2
![Uploading 7FE10607-A5B5-4C9F-95BB-6CDE3BC6ACB3.jpeg…]()

**Comment by sincethenes** [comment]
![349191E4-5DC9-479F-BCA7-6065D91EEE8E](https://user-images.githubusercontent.com/74995120/109057596-efd4ff00-76af-11eb-9789-d6d6f8ea5d21.jpeg)

**Comment by sincethenes** [comment]
![9603DB20-EDC6-424B-B913-82CD593B783E](https://user-images.githubusercontent.com/74995120/109057658-01b6a200-76b0-11eb-9e27-d85fca23302d.jpeg)

**Comment by tjanas** [comment]
Can you confirm that you updated your core files when you updated the firmware?

**Comment by sincethenes** [comment]
I’m on a set right now. How do I check, and I’ll do it later tonight?

**Comment by tjanas** [comment]
@sincethenes make sure you download the latest updated [SD System Card Structure](https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/blob/main/firmware/SD%20Card%20System%20Structure.zip) and extract those so they overwrite the existing ones on your sd card.

**Comment by sincethenes** [comment]
I’m getting a 404 error on that link @tjanas . Also from the download link to the SD System Card Structure on the National-Mini-Noir-Jailbreak page.

**Comment by sincethenes** [comment]
Not National, NT. (Autocorrect

**Comment by tjanas** [comment]
> I’m getting a 404 error on that link @tjanas . Also from the download link to the SD System Card Structure on the Nt-Mini-Noir-Jailbreak page.

Try again.

**Comment by sincethenes** [comment]
That did it. All fixed!


Sent from Yahoo Mail for iPhone


On Thursday, February 25, 2021, 11:52 AM, Terry Janas <notifications@github.com> wrote:





I’m getting a 404 error on that link @tjanas . Also from the download link to the SD System Card Structure on the Nt-Mini-Noir-Jailbreak page.


Try again.
